  
# This file is used by the "figaro" gem to allow you to store and use
# environment variables in the app without having to set them via the
# command line each time you run the app in development. Another advantage
# is that you can make changes in a production environment (such as Heroku)
# by simply changing the value of the environment variable, as opposed to
# making code changes and having to push them to apply the new setting.
# Read more about figaro here: https://github.com/laserlemon/figaro

# Note that changes to this file require a server restart to take effect.

SENDER_EMAIL: 'info@example.com'

GOOGLE_KEY: 'AIzaSyC4afmclHu1GvV7YpunKJQ-8EduulAbsMk'
GOOGLE_CLIENT_ID: '217474556298-gm3kfh6jbt5ascfnr7pt2m1inpqdskom.apps.googleusercontent.com'
GOOGLE_EMAIL_ADDRESS: '217474556298-gm3kfh6jbt5ascfnr7pt2m1inpqdskom@developer.gserviceaccount.com'
GOOGLE_FINGERPRINT: "1783b5bb2dad0565b720a12c1003ca06fb2d83d5"


###########################
#
# SETTINGS FOR DEVELOPMENT
#
###########################
development:
  DEFAULT_PER_PAGE: '30'
  MAX_PER_PAGE: '50'
  REPORTING_APP: '/reporting'

###############################################################################
#
# SETTINGS FOR PRODUCTION.
#
# Run `figaro heroku:set -e production -a your_app_name` to set them on Heroku.
#
###############################################################################
production:
  DEFAULT_PER_PAGE: '30'
  MAX_PER_PAGE: '50'
  EXPIRES_IN: '5'
  TLD_LENGTH: '2'
  ENABLE_HTTPS: 'yes'
  REPORTING_APP: 'http://pollwatch.us'

###########################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY.
#
###########################################
test:
  DEFAULT_PER_PAGE: '30'
  MAX_PER_PAGE: '50'
  ADMIN_APP_TOKEN: testing123
